// Kysely instance and connection pool.
//
// `types.ts` is GENERATED by kysely-codegen from the live database and committed.
// The flow is one-directional (`architecture.md §4.6`):
//
//     Data Model DDL -> migration SQL -> database -> generated types
//
// Never hand-edit the generated file. Fixing a type error there desynchronizes the
// code from the database, which is precisely where invariants are enforced (§4.1).

import { Kysely, PostgresDialect } from 'kysely';
import pg from 'pg';
import type { DB } from './types.js';

// Postgres returns numeric(8,2) as a string to avoid float precision loss. Weights
// are money-like and summed for NTFB reporting, so that is the behavior we want —
// parse deliberately at the edge, never by a global float cast here.

const connectionString = process.env['DATABASE_URL'];
if (!connectionString) {
  throw new Error('DATABASE_URL is not set');
}

// Sized for the operating envelope, not for load: peak ~5 simultaneous users,
// ceiling well under 10 (`product-requirement.md §6`). R3 is explicitly not
// engineered for throughput.
export const pool = new pg.Pool({ connectionString, max: 10 });

export const db = new Kysely<DB>({
  dialect: new PostgresDialect({ pool }),
});

export type Database = typeof db;
