// Kysely instance and connection pool.
//
// `types.ts` is NOT in the repository yet: it is GENERATED by kysely-codegen from
// the live database and committed only after the first migration runs. The flow is
// one-directional (`architecture.md §4.6`):
//
//     Data Model DDL -> migration SQL -> database -> generated types
//
// Never hand-edit the generated file. Fixing a type error there desynchronizes the
// code from the database, which is precisely where invariants are enforced (§4.1).

export {};
