/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Duty = "DRIVE" | "RECEIVE" | "REPORT";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type ShiftStatus = "CANCELLED" | "CLAIMED" | "COMPLETED" | "IN_PROGRESS" | "OPEN";

export type ShiftstopDisposition = "COLLECTED" | "PENDING" | "REASSIGNED" | "SKIPPED";

export type Tier = "ADMIN" | "STAFF" | "VOLUNTEER";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AppConfig {
  horizon_days: Generated<number>;
  id: Generated<boolean>;
  receiver_edit_window_days: Generated<number>;
  session_absolute_shared_hours: Generated<number>;
  session_idle_personal_staff_days: Generated<number>;
  session_idle_personal_volunteer_days: Generated<number>;
  session_idle_shared_minutes: Generated<number>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AppUser {
  address: string | null;
  created_at: Generated<Timestamp>;
  credential_hash: string;
  deactivated_at: Timestamp | null;
  first_name: string;
  id: Generated<string>;
  last_name: string;
  phone: string | null;
  tier: Tier;
  username: string;
}

export interface AvailabilityBlock {
  created_at: Generated<Timestamp>;
  ends_at: Timestamp;
  id: Generated<string>;
  starts_at: Timestamp;
  user_id: string;
}

export interface Category {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<string>;
  name: string;
}

export interface Device {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
}

export interface Donor {
  address: string | null;
  contact: string | null;
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<string>;
  name: string;
  note: string | null;
}

export interface Notification {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event: string;
  id: Generated<string>;
  last_attempt_at: Timestamp | null;
  payload: Generated<Json>;
  read_at: Timestamp | null;
  recipient_id: string | null;
  shift_id: string | null;
  subscription_id: string | null;
}

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PushSubscription {
  auth: string;
  created_at: Generated<Timestamp>;
  device_id: string | null;
  endpoint: string;
  id: Generated<string>;
  label: string | null;
  p256dh: string;
  revoked_at: Timestamp | null;
  user_id: string | null;
}

export interface RecurrencePattern {
  created_at: Generated<Timestamp>;
  created_by: string;
  end_date: Timestamp | null;
  end_time: string;
  id: Generated<string>;
  owner_default_id: string | null;
  route_id: string;
  start_time: string;
  weekdays: number[];
}

export interface Route {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<string>;
  name: string;
}

export interface RouteStop {
  donor_id: string;
  id: Generated<string>;
  position: number;
  route_id: string;
}

export interface Session {
  created_at: Generated<Timestamp>;
  device_id: string | null;
  expires_at: Timestamp;
  id: string;
  last_seen_at: Generated<Timestamp>;
  user_id: string;
}

export interface Shift {
  /**
   * I20 staff-assign exemption: Staff confirmed through an eligibility conflict when setting this owner. Drives S1.3's persistent banner for the owner. Never set by self-select or materialization, both of which are gated by eligible() and so can never produce a conflicting assignment.
   */
  assigned_over_conflict: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string;
  ends_at: Timestamp;
  id: Generated<string>;
  note: string | null;
  occurrence_date: Timestamp;
  owner_id: string | null;
  pickup_completed_at: Timestamp | null;
  recurrence_pattern_id: string | null;
  route_id: string;
  staff_note: string | null;
  starts_at: Timestamp;
  status: Generated<ShiftStatus>;
  truck_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
}

export interface ShiftStop {
  disposition: Generated<ShiftstopDisposition>;
  donor_id: string;
  id: Generated<string>;
  note: string | null;
  position: number;
  shift_id: string;
}

export interface Truck {
  created_at: Generated<Timestamp>;
  deactivated_at: Timestamp | null;
  id: Generated<string>;
  plate: string | null;
  truck_name: string;
}

export interface UserDuty {
  duty: Duty;
  user_id: string;
}

export interface DB {
  app_config: AppConfig;
  app_user: AppUser;
  availability_block: AvailabilityBlock;
  category: Category;
  device: Device;
  donor: Donor;
  notification: Notification;
  pgmigrations: Pgmigrations;
  push_subscription: PushSubscription;
  recurrence_pattern: RecurrencePattern;
  route: Route;
  route_stop: RouteStop;
  session: Session;
  shift: Shift;
  shift_stop: ShiftStop;
  truck: Truck;
  user_duty: UserDuty;
}
